### PR TITLE
adjust build

### PR DESCRIPTION
**Pull request by BusyJay**
So we can call `cmake::Build().register_dep("ZSTD")`.

### CODE REVIEW

**Comment by gyscos** [comment]
Hi, and thanks for the PR!

I'm not very familiar with using Cmake with Rust, so could you explain a bit what this enables?
For instance, this library uses functions declared in other headers, like `zdict.h` - should those be copied as well?

**Comment by BusyJay** [comment]
This pr sets a metadata root to building directory, which will [be set](http://doc.crates.io/build-script.html#the-links-manifest-key) as environment variable `DEP_ZSTD_ROOT`. When calling `register_dep`, the directory will [be added](http://alexcrichton.com/cmake-rs/cmake/struct.Config.html#method.register_dep) to `CMAKE_PREFIX_PATH`, which is used to search headers and libraries.

Only public interface is needed, so I just copy `zstd.h`.

**Comment by gyscos** [comment]
I'm still curious what use-case would benefit from that. Is this when integrating this rust library in a larger, multiple-languages project?

As a note, `zstd.h` is not the only public interface: `zdict.h` declares dictionary-training methods not present in `zstd.h`, used by the `dict` module for instance.

**Comment by BusyJay** [comment]
For example, rocksdb (a kv engine) optionally depend on zstd. To enable zstd support for its rust wrapper, it can either just add zstd-sys as a dependency or add zstd c sources as a submodule then write the build.rs (again).

**Comment by BusyJay** [comment]
Another example, [git-sys](https://github.com/alexcrichton/git2-rs/tree/master/libgit2-sys) depends on ssh2 and libz, but it doesn't have to add each as a submodule, but just depend on their *-sys packages instead. It's actually a [study case](http://doc.crates.io/build-script.html#building-libgit2) listed in crates.io.

**Comment by gyscos** [comment]
I'm beginning to understand: rust-rocksdb wants to build rocksdb using cmake, and have it auto-detect the zstd library?
So you don't need the rust part at all, you just want to have a zstd library that cmake can find?

In that case, `zdict.h` is definitely useful: in [`compression.h`](https://github.com/facebook/rocksdb/blob/master/util/compression.h#L39), rocksdb explicitely includes it.

Not sure if that's relevant, but zstd itself [includes a CMakeList file](https://github.com/facebook/zstd/blob/master/build/cmake/CMakeLists.txt).

**Comment by BusyJay** [comment]
Thanks for the information. I updated the pr, `zdict.h` is copied now. The `CMakeList` is useless unless there is a submodule. Although this crate may take advantage of cmake and skip the compilation details.

**Comment by gyscos** [comment]
Well, thanks for the explanations!
I'm wondering if this is enough, though. I suppose the goal is to make a structure recognizable by cmake, I think the `libzstd.a` library itself needs to be copied to `$OUT_DIR/lib`?

Looking at the current `libssh2-sys`, it seems to just be using `cmake`, and doesn't copy these files. [A previous version](https://github.com/alexcrichton/ssh2-rs/blob/5688e2bd912bb1ad8de261e5849f58b4857a6818/libssh2-sys/build.rs) apparently was:
* On unix, just using `make install` commands to copy the library and the include files in the `OUT_DIR`, thus ensuring a structure the cmake would like.
* On windows, manually copy the library and header files to `$OUT_DIR/lib` and `$OUT_DIR/include` respectively.

Also, the `zdict.h` must go directly in the `include` directory, not in a subfolder.

**Comment by BusyJay** [comment]
> ... I think the libzstd.a library itself needs to be copied to $OUT_DIR/lib?

Not necessary, as long as the library exist in CMAKE_PREFIX_PATH, which is set by `cargo:root`.

> ..  it seems to just be using cmake, and doesn't copy these files. ...

cmake-rs will set the `cargo:root` automatically. Hence library can be loaded automatically.

> .. the zdict.h must go directly in the include directory, not in a subfolder.

Fixed.

This is tested in pingcap/rust-rocksdb#159. But we only use rocksdb 5.7.3 now, which doesn't include `zdict.h` yet.

**Comment by gyscos** [comment]
Ah, I see. Looks good then! Thanks again!

**Pull request merged**
